export const sample_restaurant = [
   {
        id: '1',
        name: 'Seen',
        price: '€30-40',
        rate: 5,
        imageUrl: 'food.jpg',
        tags: ['Asian', 'Munich'],
        //keywords: ['Seen','Chinese Restaurant','Munich','Asian'],
    },
    {
        id: '2',
        name: 'Chois',
        price: '€30-40',
        rate: 4.1,
        imageUrl: 'food.jpg',
        tags: ['Asian', 'Frankfurt'],
       // keywords: ['Seen','Chinese Restaurant','Munich','Asian','Hotpot'],
    },
    {
        id: '3',
        name: 'Magic Woks',
        price: '€10-20',
        rate: 4.5,
        imageUrl: 'food.jpg',
        tags: ['Asian', 'Munich'],
    },
    {
        id: '4',
        name: 'Bubble Tea',
        price: '€5-10',
        rate: 3,
        imageUrl: 'food.jpg',
        tags: ['Asian', 'Munich'],
    },
    {
        id: '5',
        name: 'Pizza',
        price: '€5-10',
        rate: 3.5,
        imageUrl: 'food.jpg',
        tags: ['Italian', 'Munich'],
    },
    {
        id: '6',
        name: 'Sushi',
        price: '€20-30',
        rate: 2,
        imageUrl: 'food.jpg',
        tags: ['Asian', 'Frankfurt'],
    },
    {
        id: '7',
        name: 'Doenner',
        price: '€5-10',
        rate: 4.4,
        imageUrl: 'food.jpg',
        tags: ['Turkish', 'Munich'],
    },
];

export const sample_tags = [
    {name:"All", count: 7},
    {name:"Asian", count: 5},
    {name:"Munich", count: 5},
    {name:"Frankfurt", count: 2},
    {name:"Italian", count: 1},
    {name:"Turkish", count: 1},
];